### ISSUE TITLE
what is the current PDK_HASH 

### ISSUE THREAD

**Issue by emfhasan** [google/open-source-pdks#24]
when i try to enable sk13o using the following commads: 

PDK_HASH = 'fa87f8f4bbcc7255b6f0c0fb506960f531ae2392'
PDK_ROOT = '/root/.volare/volare/sky130/versions'

pip install --upgrade --no-cache-dir volare
volare enable --pdk sky130 {PDK_HASH} 

i got following error:
Version {PDK_HASH} not found either locally or remotely.
Try volare build {PDK_HASH}.

when tried to build {PDK_HASH} it gives:  Cannot update paths and switch to branch 'current' at the same time.\nDid you intend to checkout '{fa87f8f4bbcc7255b6f0c0fb506960f531ae2392}' which can not be resolved as commit?\n"
what does that mean??

**Comment by mithro** [comment]
Volare is a project build and maintained by @efabless and not Google.

**Comment by mithro** [comment]
You will want to report the issue to https://github.com/efabless/volare
